spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/posttest
    username: guchiboard
    password: posttest
      
  mFile:
    local: true
    
cloud.aws:
  credentials:
    accessKey: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_ACCESS_KEY}

  stack:
    auto: false
  region:
    static: AP_NORTHEAST_1
  
mybatis:
  configuration:
    map-underscore-to-camel-case: true